// SPDX-License-Identifier: AGPL-3.0-or-later
// A TRANSLATION CANNOT CONTAIN MARKUP — the one injection vector the hand audit of 2026-08-26 left open (issue #51).
//
// ========================= WHAT THE AUDIT CHECKED =========================
// No `innerHTML`/`insertAdjacentHTML` in the tree receives outside text — checked by DATA SOURCE, which is what
// matters, not by call site:
//
//   · audio device name (the user renames a Bluetooth device)  → `textContent`, never markup
//   · system voice name (`speechSynthesis.getVoices`)          → `textContent`
//   · gamepad wizard progress                                  → `textContent`
//   · gamepad id (a forged USB device declares any name)       → only a lookup KEY (`padLayoutFromId`, `padMapFor`);
//                                                                never interpolated
//   · storage values                                           → none reaches markup
//
// WHAT IS LEFT, and the reason for this file: i18n texts go RAW into template literals that become `innerHTML`. That is
// safe because the dictionaries are ours and carry no markup. But "safe because nobody has written markup yet" is not a
// guarantee: it is a habit. A contributed translation, pasted from a document or generated by a tool, may bring a tag,
// and it would run inside the game.
//
// ⚠️ THIS GATE DOES NOT PROVE "NO XSS". It closes ONE vector. Two things remain the writer's responsibility:
//   · when the letter-grid screen exists (ADR-0041), TYPED text reaches the interface — and then the target must be
//     `textContent`, or escaped;
//   · any new `innerHTML` that interpolates something other than i18n, a number or an enumerated key.
//
// MUTATION CHECKED: putting `'x': '<b>oi</b>'` in `app/js/i18n/pt.ts`, the case fails naming `pt.ts  x`.
import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = join(process.cwd(), 'app', 'js', 'i18n');

/** `key: 'value'` (or double quotes), with escapes respected. */
const ENTRADA = /['"]?([\w.$-]+)['"]?\s*:\s*(['"])((?:\\.|(?!\2).)*)\2/g;

/** Opens a tag: `<` followed by a letter, `/` or `!`. `1 < 2` and `a<b` do not match. */
const ABRE_TAG = /<[a-zA-Z/!]/;

function entradas() {
  const out = [];
  for (const f of readdirSync(DIR).filter((n) => n.endsWith('.ts'))) {
    const src = readFileSync(join(DIR, f), 'utf8');
    for (const m of src.matchAll(ENTRADA)) out.push({ arquivo: f, chave: m[1], valor: m[3] });
  }
  return out;
}

describe('i18n · nenhuma tradução carrega markup', () => {
  it('[Zero] o gate está lendo os dicionários de verdade', () => {
    // Without this, renaming the folder would leave the case below green by measuring nothing — and a security gate
    // that passes because it is empty is worse than none, because it gives the feeling of coverage.
    const todas = entradas();
    expect(todas.length).toBeGreaterThan(900);
    expect(new Set(todas.map((e) => e.arquivo)).size).toBeGreaterThanOrEqual(3); // pt, en, es
  });

  it('[Right] nenhuma entrada abre uma tag', () => {
    const suspeitas = entradas()
      .filter((e) => ABRE_TAG.test(e.valor))
      .map((e) => `${e.arquivo}  ${e.chave}  ->  ${e.valor.slice(0, 60)}`);
    expect(suspeitas, 'tradução com markup — ela vai CRUA para dentro de innerHTML: ' + suspeitas.join(' | ')).toEqual([]);
  });

  it('[Interface] a regra distingue tag de sinal de menor — senão vira ruído e é desligada', () => {
    expect(ABRE_TAG.test('<b>negrito</b>')).toBe(true);
    expect(ABRE_TAG.test('<img src=x onerror=alert(1)>')).toBe(true);
    expect(ABRE_TAG.test('</div>')).toBe(true);
    expect(ABRE_TAG.test('use 1 < 2 para comparar')).toBe(false);
    expect(ABRE_TAG.test('pressione <- para voltar')).toBe(false);
  });
});
