// SPDX-License-Identifier: AGPL-3.0-or-later
// tools/png-write.mjs — WRITES a PNG from pixels, with no dependency at all.
//
// An AUTHORING tool, not the game's: it lives in `tools/`, not in `app/`, and nothing in the package imports it. It
// exists because the scenes' background art may come to be generated by code, and generating art needs an encoder as
// much as checking it needed a decoder (see tests/city-tiles, which left with the tile world; `tests/png-write` holds
// this encoder).
//
// The format, in the part that matters: signature + IHDR + IDAT (node's own zlib) + IEND, each chunk with a CRC-32.
// Rows go with filter 0 (none) — compression is lost and a file anyone can re-read by hand is gained, which for
// reference art is worth more than bytes.
import { deflateSync } from 'node:zlib';
import { writeFileSync } from 'node:fs';

const TABELA_CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = TABELA_CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function bloco(tipo, dados) {
  const cabeca = Buffer.alloc(8);
  cabeca.writeUInt32BE(dados.length, 0);
  cabeca.write(tipo, 4, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([Buffer.from(tipo, 'ascii'), dados])), 0);
  return Buffer.concat([cabeca, dados, crc]);
}

/**
 * `pixels` is a [height][width] matrix of `[r,g,b,a]` (a optional, 255). Returns the PNG's Buffer.
 * Always 8-bit RGBA: one format, no palette and no choice, because whoever generates art here does not want to decide
 * the encoding on every call — they want to look at the drawing.
 */
export function encodePng(pixels) {
  const h = pixels.length, w = pixels[0].length;
  const raw = Buffer.alloc(h * (1 + w * 4));
  let p = 0;
  for (let y = 0; y < h; y++) {
    raw[p++] = 0; // filtro 0: linha crua
    for (let x = 0; x < w; x++) {
      const [r, g, b, a = 255] = pixels[y][x];
      raw[p++] = r; raw[p++] = g; raw[p++] = b; raw[p++] = a;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8;   // bits por canal
  ihdr[9] = 6;   // RGBA
  ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0; // deflate, default filter, no interlacing
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    bloco('IHDR', ihdr),
    bloco('IDAT', deflateSync(raw, { level: 9 })),
    bloco('IEND', Buffer.alloc(0)),
  ]);
}

/** Grava direto. `pixels` como acima. */
export function writePng(caminho, pixels) {
  writeFileSync(caminho, encodePng(pixels));
}
